#!/bin/bash

## call this file as
##   sbatch --job-name=diff_sim1_${1}_${2} sbatch_sim1 dir

#SBATCH --ntasks=50
#SBATCH --partition=broadwl
#SBATCH --time=1-12:00:00
##SBATCH --exclusive

SCRATCH=/scratch/midway2/mkolar
JULIA=/project2/mkolar/julia-1.5.0/bin/julia

mkdir -p $SCRATCH/diffTest/sim6
mkdir -p $SCRATCH/output/sim6

module load parallel

parallel --delay .2 -j $SLURM_NTASKS --joblog __$SLURM_JOB_NAME.runtask.log --resume srun --exclusive -N1 -n1 --error=$SCRATCH/output/sim6/$SLURM_JOB_NAME.err.{1} --output=$SCRATCH/output/sim6/$SLURM_JOB_NAME.out.{1} $JULIA sim6.jl {1} ${1} ${2} $SCRATCH/diffTest/sim6 ::: {1..1000}
