#!/bin/bash

## call this file as
##   sbatch --job-name=diff_sim1_${1}_${2} sbatch_sim1 dir

#SBATCH --ntasks=50
#SBATCH --partition=broadwl
#SBATCH --time=1-12:00:00

module load parallel
module load hdf5

SCRATCH_PATH=/scratch/midway2/mkolar
TMPOUT=$SCRATCH_PATH/output/sim8_o_power
OUT=$SCRATCH_PATH/diffTest/sim8_o_power_${1}_${2}
JULIA_PATH=/home/mkolar/project-midway/julia-1.5.0/bin/julia
FNAME=sim8_o_power.jl

mkdir -p $OUT
mkdir -p $TMPOUT


parallel --delay .2 -j $SLURM_NTASKS --joblog __$SLURM_JOB_NAME.runtask.log --resume srun --exclusive -N1 -n1 --error=$TMPOUT/$SLURM_JOB_NAME.err.{1} --output=$TMPOUT/$SLURM_JOB_NAME.out.{1} $JULIA_PATH $FNAME {1} ${1} ${2} $OUT ::: {1..1000}
