#!/bin/bash

## call this file as
##   sbatch --job-name=diff_sim1_${1}_${2} sbatch_sim1 dir

#SBATCH --ntasks=28
##SBATCH --job-name=diff_sim1
#SBATCH --partition=standard
#SBATCH --time=2-00:00:00
#SBATCH --exclusive

mkdir -p /scratch/mkolar/diffTest/sim1
mkdir -p /scratch/mkolar/output/sim1


parallel --delay .2 -j $SLURM_NTASKS --joblog __$SLURM_JOB_NAME.runtask.log --resume srun --exclusive -N1 -n1 --error=/scratch/mkolar/output/sim1/$SLURM_JOB_NAME.err.{1} --output=/scratch/mkolar/output/sim1/$SLURM_JOB_NAME.out.{1} /home/mkolar/mkolar_space/julia-1.1.1/bin/julia sim1.jl {1} ${1} ${2} /scratch/mkolar/diffTest/sim1 ::: {1..1000}
